Spec: clarify & refactor the relationship between channel and connection state
ably/specification pull request #193
Opened 2024-06-17 14:08 UTC by SimonWoolf

Internal discussion: https://ably-real-time.slack.com/archives/C8SPU4589/p1718631357934699?thread_ts=1718115075.720879&cid=C8SPU4589

This is not a behaviour change, just a tweak to clarify, since from the existing wording of RTL4i in particular ("do the operation once the connection state is @CONNECTED@") wasn't very clear. Refactored the concrete action into RTL3d and made RTL4i and RTN15c6/7 just reference that.

2024-06-17 16:35 UTC, sacOO7 requested changes

2024-06-17 16:35 UTC, sacOO7 commented on textile/features.textile
> +** @(RTL4i)@ If the connection state is @CONNECTING@ or @DISCONNECTED@, the channel should be put into the @ATTACHING@ state. (An attach will be triggered once the the connection becomes @CONNECTED@
```suggestion
** @(RTL4i)@ If the connection state is @CONNECTING@ or @DISCONNECTED@, the channel should be put into the @ATTACHING@ state. (Attach message will be sent once the the connection becomes @CONNECTED@ per @RTL3d@).
```

2024-06-18 09:06 UTC, ttypic approved these changes
LGTM

2024-06-18 09:10 UTC, sacOO7 approved these changes
lgtm

2024-06-18 09:32 UTC, merged