Clarify how `echoMessages` should be implemented
ably/specification pull request #198
Opened 2024-07-17 11:54 UTC by lawrence-forooghian

2024-07-17 12:20 UTC, sacOO7 requested changes

2024-07-17 14:53 UTC, VeskeR approved these changes

2024-07-17 14:56 UTC, maratal commented on textile/features.textile
> +** @(RTN2b)@ @echo@ should be @true@ if the @echoMessages@ client option is true; else it should be @false@, which will prevent messages published by the client being echoed back
I agree with @sacOO7, this sentence can be simplified.

2024-07-18 12:05 UTC, lawrence-forooghian commented on textile/features.textile
> +** @(RTN2b)@ @echo@ should be @true@ if the @echoMessages@ client option is true; else it should be @false@, which will prevent messages published by the client being echoed back
But the `echoMessages` client option is a boolean, and the `echo` connection parameter is a string, right? It’s not obvious that `true` maps to `"true"` and `false` maps to `"false"`.

2024-07-18 12:11 UTC, sacOO7 commented on textile/features.textile
> +** @(RTN2b)@ @echo@ should be @true@ if the @echoMessages@ client option is true; else it should be @false@, which will prevent messages published by the client being echoed back
Okay, got it

2024-07-18 12:11 UTC, sacOO7 approved these changes
Lgtm

2024-07-18 12:28 UTC, merged

2026-05-05 09:41 UTC, SimonWoolf commented
@lawrence-forooghian what was the purpose of this change?

And this isn't exactly a clarification, it's a material change in behaviour -- before this pr a lib only needs to set the echo qs param if the user specifies echoMessages=false, after this pr it must set it always?

2026-05-07 13:55 UTC, lawrence-forooghian commented
The intention of this change was to make it clear what a client needed to do in order to implement the behaviour described in RTC1a: "If false, it prevents messages originating from this connection being echoed back on the same connection". It does this by stating that this is achieved by using the `echo` connection query param.

> it's a material change in behaviour -- before this pr a lib only needs to set the echo qs param if the user specifies echoMessages=false, after this pr it must set it always?

I don't agree — even before this, it still said "`echo` should be `true` by default" i.e. it still implied that the client was always meant to send `echo`.

But yes, if `true` is the _server_ default then I agree with #465; I'll do a PR to address.

2026-05-07 14:06 UTC, SimonWoolf commented
> even before this, it still said "echo should be true by default"

Fair point, that item was very poorly phrased -- it's one of those very early ones which were terrible for confusing SDK implementation requirements with expected overall system behaviour