Spec: SUBSCRIBE mode renamed to MESSAGE_SUBSCRIBE
ably/specification pull request #212
Opened 2024-10-21 13:29 UTC by mschristensen

The `SUBSCRIBE` channel mode has now been renamed to `MESSAGE_SUBSCRIBE` to better match the existing `PRESENCE_SUBSCRIBE` mode as well as upcoming channel state related modes (to be addressed separately), and for better parity with capability strings.

SEE: https://github.com/ably/realtime/discussions/6352

2024-10-21 21:59 UTC, SimonWoolf requested changes
from https://github.com/ably/realtime/discussions/6352:
> But note: for backwards compatibility, the existing `SUBSCRIBE` mode retains its current meaning, synonymous with `MESSAGE_SUBSCRIBE`. 
else this will be a breaking change for people who are currently specifying SUBSCRIBE. (which would be fine in a major sdk version break, but that's not being proposed here, and it would be way overkill when we can just make it backwards-compatible)

2024-10-22 11:19 UTC, mschristensen commented
@SimonWoolf I've updated to try to clarify that `MESSAGE_SUBSCRIBE` is synonymous with `SUBSCRIBE` and that the latter is still supported by still including it in the spec. Please let me know if you think there's a way to express this more clearly than what I've done

2024-10-22 23:01 UTC, SimonWoolf commented
I think it's worth making clear which one is the main one going forward and which one is the deprecated synonym, eg for purposes of exposing in channel.modes (RTL4m); the PR in its current state has them symmetric.

(I don't think we need to worry too much about backwards compatibility re rtl4m, I doubt anyone's parsing that; but we definitely do for taking an array of modes in channeloptions)

2024-10-23 10:13 UTC, mschristensen commented
@SimonWoolf updated

2024-10-24 01:32 UTC, SimonWoolf approved these changes

2024-10-24 11:16 UTC, merged